export const SPRINT_DATA = {
  startDate: new Date("2025-11-28"),
  endDate: new Date("2025-12-25"),
  currentDate: new Date("2025-11-29"),
  phases: [
    {
      name: "Foundation Sprint",
      days: "1-7",
      dates: "Nov 28 - Dec 4",
      color: "#1E293B",
      bgColor: "linear-gradient(135deg, #F1F5F9 0%, #E2E8F0 100%)",
      hoursPerDay: "12-15",
      focus: "Python, C#, Unity, XR, CV, AI basics",
      startDay: 1,
      endDay: 7,
    },
    {
      name: "Build Sprint + Events",
      days: "8-20",
      dates: "Dec 5 - Dec 17",
      color: "#FFFFFF",
      bgColor: "linear-gradient(135deg, #60A5FA 0%, #93C5FD 100%)",
      hoursPerDay: "8-20",
      focus: "Ship Project 3, attend events, network",
      startDay: 8,
      endDay: 20,
    },
    {
      name: "Consolidation",
      days: "21-28",
      dates: "Dec 18 - Dec 25",
      color: "#FFFFFF",
      bgColor: "linear-gradient(135deg, #94A3B8 0%, #CBD5E1 100%)",
      hoursPerDay: "5-8",
      focus: "Reflect, polish portfolio, open source",
      startDay: 21,
      endDay: 28,
    },
  ],
  courses: [
    {
      id: 1,
      name: "Python Fundamentals",
      resource: "DeepLearning.AI",
      hours: 10,
      phase: 1,
      days: "1-2",
      category: "Python/AI",
      topics: [
        "Variables & data types",
        "Loops & functions",
        "API calls & JSON parsing",
        "Error handling",
      ],
      prerequisites: null,
      url: "https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers/",
      overview:
        "Master Python basics with hands-on exercises. Learn to write clean, efficient code and work with APIs for real-world applications.",
      intensity: 2,
    },
    {
      id: 2,
      name: "LLM Integration",
      resource: "KDnuggets + DeepL.AI",
      hours: 8,
      phase: 1,
      days: "2-3",
      category: "Python/AI",
      topics: [
        "OpenAI API",
        "Prompt engineering",
        "Streaming responses",
        "Token counting",
      ],
      prerequisites: 1,
      url: "https://www.deeplearning.ai/short-courses/building-systems-with-chatgpt/",
      overview:
        "Build production-ready LLM applications. Learn prompt engineering, API integration, and how to handle streaming responses efficiently.",
      intensity: 3,
    },
    {
      id: 3,
      name: "C# Fundamentals",
      resource: "Code Monkey YouTube",
      hours: 15,
      phase: 1,
      days: "1-3",
      category: "C#/Unity",
      topics: [
        "Variables & types",
        "Classes & OOP",
        "Methods & events",
        "Unity scripting",
      ],
      prerequisites: null,
      url: "https://www.youtube.com/watch?v=IFayQioG71A",
      overview:
        "Complete C# crash course for Unity development. From basic syntax to object-oriented programming with practical game examples.",
      intensity: 3,
    },
    {
      id: 4,
      name: "Unity Fundamentals",
      resource: "Code Monkey course",
      hours: 8,
      phase: 1,
      days: "3-4",
      category: "C#/Unity",
      topics: [
        "Editor & GameObjects",
        "Scenes & transforms",
        "Physics & colliders",
        "Prefabs",
      ],
      prerequisites: 3,
      url: "https://learn.unity.com/course/create-with-code",
      overview:
        "Official Unity beginner course. Learn the Unity editor, scene management, physics system, and prefab workflows through hands-on projects.",
      intensity: 2,
    },
    {
      id: 5,
      name: "XR Interaction Toolkit",
      resource: "Meta + Rob Shocks",
      hours: 12,
      phase: 1,
      days: "4-5",
      category: "XR",
      topics: [
        "XR Rig setup",
        "Teleportation",
        "Grab interactions",
        "Hand tracking basics",
      ],
      prerequisites: 4,
      url: "https://developer.oculus.com/documentation/unity/unity-tutorial-hello-vr/",
      overview:
        "Build immersive VR experiences for Meta Quest. Master XR interactions, locomotion systems, and hand tracking integration.",
      intensity: 4,
    },
    {
      id: 6,
      name: "Computer Vision",
      resource: "freeCodeCamp",
      hours: 12,
      phase: 1,
      days: "5-7",
      category: "Computer Vision",
      topics: [
        "OpenCV",
        "Real-time detection",
        "Object tracking",
        "Hand & pose detection",
      ],
      prerequisites: 1,
      url: "https://www.youtube.com/watch?v=oXlwWbU8l2o",
      overview:
        "Comprehensive OpenCV tutorial covering image processing, object detection, and real-time tracking. Build practical CV applications from scratch.",
      intensity: 4,
    },
    {
      id: 7,
      name: "LLM Agents & Tool Calling",
      resource: "LangChain docs",
      hours: 10,
      phase: 1,
      days: "6-7",
      category: "Python/AI",
      topics: [
        "Agent architecture",
        "Tool calling",
        "Structured outputs",
        "Multi-step reasoning",
      ],
      prerequisites: 2,
      url: "https://python.langchain.com/docs/tutorials/agents/",
      overview:
        "Advanced LLM patterns with LangChain. Build autonomous agents that can use tools, reason through complex tasks, and generate structured outputs.",
      intensity: 5,
    },
    {
      id: 8,
      name: "SensAI Pre-Hack Workshop",
      resource: "YouTube + SensAI Kits",
      hours: 8,
      phase: 1,
      days: "6-7",
      category: "XR",
      topics: [
        "Context-aware AI",
        "Microgestures",
        "PCA overview",
        "SensAI Kits exploration",
      ],
      prerequisites: 5,
      url: "https://www.youtube.com/@SensAI_XR",
      overview:
        "Prepare for the SensAI Hackathon. Learn context-aware AI, microgesture detection, and explore the SensAI development kits.",
      intensity: 3,
    },
    {
      id: 9,
      name: "XR+AI Integration",
      resource: "Meta PCA tutorials",
      hours: 6,
      phase: 1,
      days: "7",
      category: "Integration",
      topics: [
        "Passthrough Camera Access",
        "Real-time AI fusion",
        "Latency optimization",
        "Production patterns",
      ],
      prerequisites: "5,6,7",
      url: "https://developer.oculus.com/documentation/unity/unity-passthrough/",
      overview:
        "Combine XR and AI for cutting-edge applications. Access passthrough cameras, integrate real-time AI processing, and optimize for performance.",
      intensity: 5,
    },
  ],
  projects: [
    {
      id: 1,
      name: "AI LLM Chatbot",
      description:
        "Build a Python chatbot using OpenAI API and deploy it to Streamlit Cloud. Learn API integration, prompt engineering, and web deployment.",
      phase: 1,
      days: "1-3",
      hours: 12,
      difficulty: "Beginner",
      techStack: ["Python", "OpenAI API", "Streamlit"],
      deliverables: [
        "Python script with API integration",
        "Chat interface with Streamlit",
        "Deployed to Streamlit Cloud",
        "GitHub repo with documentation",
        "Tested with 5+ conversation types",
      ],
    },
    {
      id: 2,
      name: "VR Interactive Scene",
      description:
        "Create a VR scene on Meta Quest 3 with grabbable objects, teleportation, and hand tracking. Deploy and test on physical hardware.",
      phase: 1,
      days: "3-7",
      hours: 18,
      difficulty: "Intermediate",
      techStack: ["Unity", "C#", "Meta XR SDK", "Hand Tracking"],
      deliverables: [
        "VR scene with XR Rig",
        "3-4 grabbable objects",
        "Teleportation system",
        "Interactive UI in VR",
        "Deployed APK to Quest",
        "72+ FPS performance verified",
      ],
    },
    {
      id: 3,
      name: "Context-Aware XR+AI App",
      description:
        "Full-stack app combining Quest passthrough camera, OpenCV detection, GPT-4 vision, and VR overlay. The flagship portfolio piece.",
      phase: 2,
      days: "7-18",
      hours: 40,
      difficulty: "Advanced",
      techStack: [
        "Unity",
        "C#",
        "Python",
        "OpenCV",
        "GPT-4 Vision API",
        "Meta PCA",
      ],
      deliverables: [
        "Passthrough camera frame capture",
        "Real-time object detection",
        "LLM integration for reasoning",
        "VR overlay visualization",
        "60+ FPS performance",
        "End-to-end working demo",
        "GitHub repo with full docs",
        "Hackathon submission",
      ],
    },
  ],
  events: [
    {
      id: 1,
      name: "SensAI Hack - XR AI Hackathon",
      date: "2025-12-05",
      endDate: "2025-12-07",
      time: "Friday 10 AM - Sunday 6 PM",
      location: "Frontier Tower, 995 Market St, San Francisco",
      type: "Hackathon",
      description:
        "72-hour hackathon building XR+AI apps on Meta Quest. $1.5M in prizes, networking with 500+ XR developers.",
      prep: [
        "Join SensAI Discord Dec 4",
        "Form team (3+ people)",
        "Review SensAI Kits",
        "Prepare 2-3 app concepts",
      ],
      url: "https://sensaihack.com/sanfrancisco/",
      importance: "CRITICAL",
    },
    {
      id: 2,
      name: "Global AI Expo 2025",
      date: "2025-12-10",
      time: "1 PM - 5 PM",
      location: "San Jose Convention Center, San Jose",
      type: "Conference/Expo",
      description:
        "Large AI expo with 4 tracks: Foundational AI, Agentic AI, Applied AI, Startup Launchpad. 2000+ attendees.",
      prep: [
        "Register online",
        "Prepare elevator pitch",
        "Plan which halls to visit",
      ],
      url: "https://www.globalaiexpo.com/",
      importance: "HIGH",
    },
    {
      id: 3,
      name: "SF AI Week 2025",
      date: "2025-12-11",
      endDate: "2025-12-17",
      time: "Varies by workshop (1-2 hrs each)",
      location: "San Francisco Public Library & various",
      type: "Workshop Series",
      description:
        "Weekly workshops on AI applications: Travel with AI, Cooking with AI, Music & AI, Practical AI for Small Business.",
      prep: [
        "Check SFPL website for schedule",
        "RSVP to 2-3 workshops",
        "Bring laptop",
      ],
      url: "https://www.sf.gov/event-20251211-sf-ai-week-2025",
      importance: "MEDIUM",
    },
    {
      id: 4,
      name: "Built On Bedrock Demo Night",
      date: "2025-12-16",
      time: "5 PM - 7 PM",
      location: "AWS, 525 Market St, San Francisco",
      type: "Demo Night/Networking",
      description:
        "Agentic AI demos from startups using AWS Bedrock. Mix of pitches and networking.",
      prep: [
        "RSVP on AWS Startups",
        "Prepare 1-min intro",
        "Bring business cards",
      ],
      url: "https://aws.amazon.com/startups/",
      importance: "HIGH",
    },
    {
      id: 5,
      name: "Dr. Fei-Fei Li in Conversation",
      date: "2025-12-17",
      time: "10 AM - 12 PM",
      location: "San Francisco Public Library Main, 100 Larkin St",
      type: "Keynote",
      description:
        'The Godmother of AI discussing world models, embodied AI, and the future of vision systems. Author talk for "The Worlds I See".',
      prep: [
        "RSVP early (expect 200+ people)",
        "Arrive 15 min early",
        "Consider reading book summary",
      ],
      url: "https://sfpl.org/events/",
      importance: "CRITICAL",
    },
    {
      id: 6,
      name: "SF AI Engineers Meetup",
      date: "2025-12-03",
      time: "6 PM - 8 PM",
      location: "House of AI, 40 Boardman Pl, San Francisco",
      type: "Meetup",
      description:
        "Monthly tech talk with Google, Nexla, and Anon engineers. Open discussion on production AI systems.",
      prep: ["RSVP on Meetup.com", "Prepare 2-3 questions"],
      url: "https://www.meetup.com/san-francisco-ai-engineers/",
      importance: "MEDIUM",
    },
    {
      id: 7,
      name: "AI & Tech Mixer",
      date: "2025-12-10",
      time: "7 PM - 9 PM",
      location: "Toy Soldier, 52 Belden Pl, San Francisco",
      type: "Networking",
      description:
        "Casual happy hour with AI/ML engineers and founders. Free drinks + networking.",
      prep: ["Optional RSVP", "Just show up and talk"],
      url: "",
      importance: "LOW",
    },
  ],
  dailySchedule: [
    {
      day: 1,
      date: "2025-11-28",
      phase: 1,
      blocks: [
        { name: "Morning (6 hrs)", topic: "Python Fundamentals", hours: 6 },
        { name: "Afternoon (4 hrs)", topic: "C# Basics", hours: 4 },
        { name: "Evening (3 hrs)", topic: "Setup & Install", hours: 3 },
      ],
      totalHours: 13,
    },
    {
      day: 2,
      date: "2025-11-29",
      phase: 1,
      blocks: [
        { name: "Morning (6 hrs)", topic: "LLM Integration", hours: 6 },
        { name: "Afternoon (5 hrs)", topic: "C# Advanced", hours: 5 },
        { name: "Evening (4 hrs)", topic: "Project 1 Start", hours: 4 },
      ],
      totalHours: 15,
    },
  ],
};

export const INITIAL_STATE = {
  currentTab: "dashboard",
  hoursCompleted: 0,
  projectsCompleted: [false, false, false],
  coursesCompleted: Array(9).fill(false),
  eventsAttended: Array(7).fill(false),
  deliverables: {
    1: Array(5).fill(false),
    2: Array(6).fill(false),
    3: Array(8).fill(false),
  },
};
